signing.keyId=85DBBA59
signing.password=9292
signing.secretKeyRingFile=secring.gpg

ossrhUsername=33IyeTgl
ossrhPassword=J1hJ/L4il9HFP+IPLerSaIN7M5ZNciFWsup2+zVC4qUA

# gpg -K --keyid-format short
# gpg --export-secret-keys 85DBBA59  > secring.gpg
# gpg --send-keys 85DBBA59 --keyserver keyserver.ubuntu.com
